# Generated by Django 3.2.5 on 2024-07-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_t', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterComment',
            fields=[
                ('supporter_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('commentaires', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_t.customuser')),
            ],
        ),
    ]
